
userpath('/home/s1533104/ecmc_dissertation/Matlab')

%% Import data from text file.
% Script for importing data from the following text file:
%
%    /home/s1533104/ecmc_dissertation/Matlab/observables.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2019/06/29 14:02:37

%% Initialize variables.
filename = '/home/s1533104/ecmc_dissertation/Matlab/observables.txt';

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%24f%25f%25f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', '', 'WhiteSpace', '',  'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
Observable1 = dataArray{:, 1};
Observable2 = dataArray{:, 2};
Observable3 = dataArray{:, 3};
AverageAction = dataArray{:, 4};


%% Clear temporary variables
clearvars filename formatSpec fileID dataArray ans;
[value,dvalue,ddvalue,tauint,dtauint,Qval] = UWerr(AverageAction)
